nome = str(input('Digite seu nome: ')).strip()
nma = nome.upper()
nmin = nome.lower()
sepnome = nome.split()
tam = len(nome) - nome.count(' ')
pnom = nome.find(' ')
print('Analisando seu nome...')
print('Seu nome em letras maiusculas é {}'.format(nma))
print('Seu nome em letras minusculas é {}'.format(nmin))
print('Seu nome tem ao todo {} letras' .format(tam))
print('Seu primeiro nome tem {} letras'.format(pnom))
